name: Run APP Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Make test script executable
        run: chmod +x ./run_tests.sh

      - name: Run tests
        run: ./run_tests.sh
