name: Run APP Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build test docker image
        run: docker build -t my-book-app-test -f Dockerfile.test .

      - name: Run tests
        run: docker run --rm my-book-app-test
